### ISSUE TITLE
License & Packaging

### ISSUE THREAD

**Issue by jbfriedrich** [pulinairc/thelounge-themes#2]
Your themes are really great. I started a fork and would like to package them and publish them via NPM to make them easily installable. I have not seen a license in the repo. Would you be OK with me using the MIT license for the fork and the package repos?

**Comment by jbfriedrich** [comment]
Never mind, I just saw "ISC" in the package.json. Will use the ISC license 😄 Cheers!

**Comment by rollecode** [comment]
Thank you! This collection of themes is under our IRC community GitHub for a reason because they are in use for our IRC users at [chat.pulina.fi](https://chat.pulina.fi) and shell users [irc.pulina.fi](https://irc.pulina.fi). The main theme is using our brand colors as in the website [pulina.fi](https://pulina.fi). This is why I have not packaged them myself and because they might use some styles to actually hide things that would be normally be there.

I could re-release this as MIT under my own GitHub user and add them to npm myself. Those version would be in general use. Kinda like Dracula theme I'm maintaining [here](https://github.com/dracula/thelounge). 

I'd be interested in what you have different in your fork. Maybe we could join forces here?

**Comment by jbfriedrich** [comment]
Nothing different in my fork. Just forked it an hour ago. I just tend to fork in case the upstream goes away or is abandoned. Are the brand colors or the composition somehow copyrighted? Any icons that need to be removed? The Dracula theme is not my cup of tea — the color composition in combination with the "chat bubble" style is what intrigued me. My main reason to want to package them was the easy installation and maintenance.

**Comment by rollecode** [comment]
The colors and mobile theme are my own design so I guess the normal designer's rights apply here but as I'm open source advocate something like MIT should do. Icons are all licensed for general public.

I can package every theme as their separate repos in near future.

**Comment by jbfriedrich** [comment]
That would be really awesome! Thank you! That will make my need to packaging it myself go away 👍 . It will help a lot of people using the docker container who have to reinstall their themes after the container is destroyed/upgraded.

**Comment by rollecode** [comment]
@jbfriedrich Sorry for it taking so long, I've been very busy. I have released [thelounge-theme-midnight](https://github.com/ronilaukkarinen/thelounge-theme-midnight) in its separate repository + yarn + npm. It should work with thelounge command but I have not yet tested it out.

I noticed other themes are too outdated, I should rewrite them for the conversation layout and other fixes... I currently have no time for that, but it's rather easy to do if you want to contribute or create your own themes. So the currently up to date theme version is midnight.css.

As for the fonts, I'm not sure if they go with the theme or not... if you have time for testing the theme out via "official way", let me know how it goes.

**Comment by jbfriedrich** [comment]
Hey @ronilaukkarinen, no worries, its been quite busy on my end too. Many thanks for packaging the theme up. I tested it briefly, and so far it seems to work. The one you packaged is the one I was most interested in. If i find something broken, I'll let you know - probably together with a pull request. Again, many thanks!
